// examples/nextjs-app/app/attacker/page.tsx
import {STRATEGIES, isStrategy} from '../../lib/strategies';

export const dynamic = 'force-dynamic';

// Forged cross-site form posts. Open this page from a different origin than
// the target (for example http://127.0.0.1:3000/attacker) so the browser sends
// a foreign Origin header. It needs no client JavaScript.
// ?strategy=<name> shows only that strategy's forms.
export default async function AttackerPage({searchParams}: {
    searchParams: Promise<{strategy?: string}>;
}) {
    const origin = `http://localhost:${process.env.PORT ?? '3000'}`;
    const {strategy} = await searchParams;
    const targets = strategy && isStrategy(strategy) ? [strategy] : STRATEGIES;

    return (
        <main>
            <h1>Attacker page</h1>
            <p>
                Each form posts to the app at <code>{origin}</code> without a valid CSRF token,
                the way a malicious site would. Every submission should fail with a 403.
            </p>

            {targets.map((s) => (
                <section key={s}>
                    <h2><code>{s}</code></h2>
                    <form method="post" action={`${origin}/api/demo/${s}`}>
                        <button type="submit" id={`forge-${s}`}>Send forged request (no token)</button>
                    </form>
                    <form method="post" action={`${origin}/api/demo/${s}`}>
                        <input type="hidden" name="csrf_token" value="attacker-guessed-token" />
                        <button type="submit" id={`forge-guessed-${s}`}>
                            Send forged request (guessed token)
                        </button>
                    </form>
                </section>
            ))}

            {!strategy && (
                <section>
                    <h2>App counter (<code>CSRF_STRATEGY</code>)</h2>
                    <form method="post" action={`${origin}/api/counter`}>
                        <input type="hidden" name="amount" value="1" />
                        <button type="submit" id="forge">Send forged request</button>
                    </form>
                </section>
            )}
        </main>
    );
}

// examples/nuxt-app/pages/attacker.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Attacker Page',
  description: 'Forged cross-site requests that CSRF Armor should reject.',
})

// Must match an origin the app is served from. Open this page from a
// different origin (http://[::1]:3000/attacker) so the browser sends a
// foreign Origin header, as a real attacker site would.
const target = 'http://localhost:3000/api/submit'
</script>

<template>
  <div class="container">
    <h1>Attacker page</h1>
    <NuxtLink to="/">&larr; Back to Strategy List</NuxtLink>

    <p>
      These plain HTML forms post to <code>{{ target }}</code>, the way a
      malicious site would. Open this page at
      <code>http://[::1]:3000/attacker</code> so it runs from another origin
      (<code>nuxt dev</code> listens on <code>localhost</code> only, so
      <code>127.0.0.1</code> may be refused). Each submission should fail
      with a 403.
    </p>

    <form method="post" :action="target">
      <input type="hidden" name="data" value="forged without a token" />
      <button id="forge-no-token" type="submit">Send forged request (no token)</button>
    </form>

    <form method="post" :action="target">
      <input type="hidden" name="data" value="forged with a guessed token" />
      <input type="hidden" name="_csrf" value="attacker-guessed-token" />
      <button id="forge-guessed-token" type="submit">Send forged request (guessed token)</button>
    </form>

    <p class="hint">
      The browser withholds <code>SameSite=Lax</code> cookies on cross-site
      posts, so the CSRF cookies are missing too. The token check is what
      protects you from same-site attackers, such as a sibling subdomain.
    </p>
  </div>
</template>

<style scoped>
.container {
  max-width: 640px;
  margin: 2rem auto;
  font-family: system-ui, sans-serif;
}

code {
  background: #f0f0f0;
  padding: 0.15rem 0.4rem;
  border-radius: 3px;
  font-size: 0.9em;
}

form {
  margin: 1rem 0;
}

button {
  padding: 0.5rem 1rem;
  background: #dc2626;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
}

.hint {
  color: #666;
  font-size: 0.9rem;
}

a {
  color: #00dc82;
  text-decoration: none;
}
</style>
